version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    working_directory: ~/circleci-python
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Script
          command: python3 --version
      - run:
          name: Start Flask server
          background: true
          command: python3 app.py
  run_tests:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
           name: Run test
           command: pytest
workflows:
  build_and_test:
    jobs:
      - run_tests