version: 2.1
orbs:
  python: circleci/python@2.1.1
  jira: circleci/jira@2.0.1
jobs:
  run_tests:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
           name: Run test
           command: pytest
      - jira/notify:
            environment: staging
            environment_type: staging
            pipeline_number: <<pipeline.number>>
            pipeline_id: <<pipeline.id>>
workflows:
  main:
    jobs:
        - run_tests:
            context: Jira