version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.8.4
orbs:
    python: circleci/python@2.1.1
 
jobs:
  builds:
    working_directory: ~/Flask-calculator
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Python Version
          command: python3 --version
      - run:
          name: Start Flask server
          background: true
          command: python3 app.py
      - run: 
          name: Checking Directory
          command: pwd

      - run:
          name: Build Artifact and Archiving
          command: |
            cd /home/circleci/
            mkdir -p artifacts
            cp -r /home/circleci/Flask-calculator /home/circleci/artifacts
            cd /home/circleci/artifacts
            zip -r Flask-calculator.zip /home/circleci/artifacts/Flask-calculator/*
            cd /home/circleci/artifacts
            ls -la

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - artifacts/Flask-calculator.zip     

  run_tests:
    working_directory: ~/Flask-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps: 
      - checkout 
      - python/install-packages: 
          pkg-manager: pip 
      - run: 
           name: Run test
           command: pytest   

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            cat /etc/os-release
            sudo sed -i 's/stretch/buster/g' /etc/apt/sources.list
            sudo apt-get update

      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Deploy to Azure App Service
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az webapp deployment source config-zip -g DevOpsDemo -n CircleCI --src /home/circleci/artifacts/Flask-calculator.zip

workflows:
  build_and_test:
    jobs:
      - builds
      - run_tests
      - deploy
          