version: 2.1
executors:
  python-executor:
    docker:
      - image: circleci/python:3.8.4
orbs:
  jira: circleci/jira@2.0.1
  python: circleci/python@2.1.1
  
jobs:
  builds:
    working_directory: ~/Flask-calculator
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Script
          command: python3 --version
      - run:
          name: Start Flask server
          background: true
          command: python3 app.py
      - jira/notify:
          debug: false 
          environment: development
          environment_type: development 
          ignore_errors: true 
          job_type: build 
          oidc_token: '796785c9-293e-482c-842b-bee6cb4190f5' 
          pipeline_id: Flask-calculator 
          pipeline_number: 1
              
  run_tests:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
           name: Run test
           command: pytest
      - jira/notify:
          debug: false 
          environment: development
          environment_type: development 
          ignore_errors: true 
          job_type: build 
          oidc_token: '796785c9-293e-482c-842b-bee6cb4190f5' 
          pipeline_id: Flask-calculator 
          pipeline_number: 1
workflows:
  build_and_test:
    jobs:
      - builds:
          context: JIRA_WEBHOOK_URL
      - run_tests:
          context: JIRA_WEBHOOK_URL