version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    working_directory: ~/circleci-python
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python3 calculator_test.py  # You can replace this with your testing command
      - run:
          name: Start Flask server
          background: true
          command: python3 app.py

workflows:
  version: 2
  build-deploy:
    jobs:
      - build