version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.8.4
orbs:
    python: circleci/python@2.1.1
 
jobs:
  builds:
    working_directory: ~/Flask-calculator
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt   
      - run:
          name: Build Script
          command: |
            pwd
            chmod 777 build.sh
            ls -la
            ./build.sh
            pwd
            ls -la     
      - run: 
          name: Python Version
          command: python3 --version
      - run: 
          name: Test
          command: |
            cd /home/circleci
            ls -lrth
      - run:
          name: Artifact Archiving
          command: |
            pwd
            chmod 777 artifact.sh
            ls -la
            ./artifact.sh  

  run_tests:
    working_directory: ~/Flask-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps: 
      - checkout 
      - python/install-packages: 
          pkg-manager: pip 
      - run: 
           name: Run test
           command: pytest   
  deploy:
    working_directory: ~/Flask-calculator
    docker:
      - image: cimg/azure:2023.09
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            cat /etc/os-release
            sudo sed -i 's/stretch/buster/g' /etc/apt/sources.list
            sudo apt-get update
      - run:
          name: Azure App Service Deploy
          command: |
            pwd
            chmod 777 artifact.sh
            ls -la
            ./artifact.sh
            pwd 
            ls -lrth
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az account set --subscription $AZURE_SUBSCRIPTION_ID
            az webapp deployment source config-zip -g $AZURE_RG_NAME -n $AZURE_WEBAPP_NAME --src *.zip
            az webapp up -n $AZURE_WEBAPP_NAME -g $AZURE_RG_NAME

      - run: 
          name: Test
          command: |
            ls -lrth /home/circleci/project
      - run:
          name: Deploy to Azure App Service
          command: az webapp deployment source config-zip -g DevOpsDemo -n CircleCI --src $HOME/Flask-calculator.zip

workflows:
  build_and_test_deploy:
    jobs:
      - builds
      - run_tests
      - deploy
          