version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.8.4
orbs:
    python: circleci/python@2.1.1
 
jobs:
  builds:
    working_directory: ~/Flask-calculator
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Python Version
          command: python3 --version
      - run:
          name: Start Flask server
          background: true
          command: python3 app.py
      - run: 
          name: Checking Directory
          command: pwd

      - run:
          name: Build Artifact and Archiving
          command: |
            cd /home/circleci/
            mkdir -p artifacts
            cp -r /home/circleci/Flask-calculator /home/circleci/artifacts
            cd /home/circleci/artifacts
            zip -r Flask-calculator.zip /home/circleci/artifacts/Flask-calculator/*
            cd /home/circleci/artifacts
            ls -la

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - artifacts/Flask-calculator.zip     
                    
  run_tests:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps: 
      - checkout 
      - python/install-packages: 
          pkg-manager: pip 
      - run: 
           name: Run test
           command: pytest                
      
workflows:
  build_and_test:
    jobs:
      - builds:
          context: JIRA_WEBHOOK_URL
      - run_tests:
          context: JIRA_WEBHOOK_URL