version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    working_directory: ~/circleci-python
    executor: python-executor
    steps:
      - checkout  # Checkout your source code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Script
          command: pwd
      - run:
          name: Start Flask server
          background: true
          command: python3 app.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 tests/calculator_test.py
            
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build